import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar/Navbar'
import Cards from '@/components/cards/Cards'
import { useRouter } from 'next/router'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router=useRouter();
  const query=router?.query?.title;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.contain}>
        <Navbar /> 
        {!query && <>
          <Cards title='top_rated' />
          <Cards title='popular' />
          <Cards title='upcoming' />
        </>}
        {
          query && <Cards title='search' />
        }
      </main>
      <Footer />
      </>
  )
}
