import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar/Navbar'
import Cards from '@/components/cards/Cards'
import { useRouter } from 'next/router'
import Footer from '@/components/footer/Footer'
import { useEffect,useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router=useRouter();
  const query=router?.query?.title;
  const [user, setUser] = useState({});
  const [token, setToken] = useState('');

  useEffect(() => {
    if (typeof window !== 'undefined' && window.localStorage) {
    const users = localStorage?.getItem('MovieApp_user');
    if (users) {
      const userData = JSON?.parse(users);
      const myUser = userData?.user;
      const myToken = userData?.token;
      setToken(myToken);
      setUser(myUser);
     }
    }
  }, []);

  // check if user is logged in or not
  const isLoggedIn = token ? true : false;
  console.log('isLoggedIn', isLoggedIn);

  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.contain}>
        <Navbar isLoggedIn={isLoggedIn} user={user} /> 
        {!query && <>
          <Cards title='top_rated' isLoggedIn={isLoggedIn} user={user} />
          <Cards title='popular' isLoggedIn={isLoggedIn} user={user} />
          <Cards title='upcoming' isLoggedIn={isLoggedIn} user={user} />
          <Cards title='series' isLoggedIn={isLoggedIn} user={user} />
        </>}
        {
          query && <Cards title='search' isLoggedIn={isLoggedIn} user={user} />
        }
      </main>
      {/* <Footer /> */}
      </>
  )
}
